name: mi_card
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# "assets:" must be in same column as "uses-material-design:" cus they're children of flutter !

flutter:
  uses-material-design: true
  assets:
    - images/ouss.jpg

  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf
  - family: Source Sans Pro
    fonts:
    - asset: fonts/SourceSansPro-Regular.ttf  


 